language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

sudo: false

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer require --no-update php-coveralls/php-coveralls:^2.0
  - travis_retry composer install --no-interaction --prefer-dist

before_script:
  - mkdir -p build/logs

script:
  - ./vendor/bin/parallel-lint src tests
  - composer run phpstan
  - ./vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml
  - ./vendor/bin/phpcs src tests --standard=psr12 -sp

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
